add_newline = true
command_timeout = 200
format = """
[â”Œâ”€](bold cyan)$directory$git_branch$git_status$python$nodejs$rust
[â””â”€](bold cyan)$character
"""

[character]
error_symbol = "[âœ—](bold cyan)"
success_symbol = "[â¯](bold cyan)"

[directory]
truncation_length = 2
truncation_symbol = "â€¦/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "â‡¡${count} "
diverged   = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
behind     = "â‡£${count} "
conflicted = "î®« "
up_to_date = "ï€Œ "
untracked  = "? "
modified   = "î©± "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = "ğŸ "
style = "yellow"

[nodejs]
format = '[$symbol($version )]($style)'
symbol = "îœ˜ "
style = "green"

[rust]
format = '[$symbol($version )]($style)'
symbol = "ğŸ¦€ "
style = "red"

[cmd_duration]
format = '[â± $duration]($style)'
style = "dim yellow"
min_time = 2000

[status]
format = '[âœ— $status]($style)'
style = "bold red"
disabled = false
